name: flutter_custom_license_page
description: Customize your app's license page! flutter_custom_license_page gives you the license data, and the freedom to build your app's license page in your own style!
version: 0.0.3
homepage: https://github.com/theswerd/flutter_custom_license_page
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lint: ^1.7.2


dev_dependencies:
  flutter_test:
    sdk: flutter
